export interface Currency {
  id: string | number;
  code: string;
  name: string;
  symbol: string;
  priceUSD: number;
  image: string;
  percentageChange: number;
}

export const cryptoData: Currency[] = [
  {
    id: 1,
    code: "BTC",
    name: "Bitcoin",
    symbol: "₿",
    priceUSD: 27000,
    percentageChange: 2.5,
    image: "https://cryptologos.cc/logos/bitcoin-btc-logo.png",
  },
  {
    id: 2,
    code: "ETH",
    name: "Ethereum",
    symbol: "Ξ",
    priceUSD: 1800,
    percentageChange: -1.3,
    image: "https://cryptologos.cc/logos/ethereum-eth-logo.png",
  },
  {
    id: 3,
    code: "BNB",
    name: "Binance Coin",
    symbol: "BNB",
    priceUSD: 230,
    percentageChange: 1.0,
    image: "https://cryptologos.cc/logos/binance-coin-bnb-logo.png",
  },
  {
    id: 4,
    code: "XRP",
    name: "Ripple",
    symbol: "XRP",
    priceUSD: 0.52,
    percentageChange: 0.75,
    image: "https://cryptologos.cc/logos/xrp-xrp-logo.png",
  },
  {
    id: 5,
    code: "SOL",
    name: "Solana",
    symbol: "SOL",
    priceUSD: 22,
    percentageChange: 3.4,
    image: "https://cryptologos.cc/logos/solana-sol-logo.png",
  },
  {
    id: 6,
    code: "DOGE",
    name: "Dogecoin",
    symbol: "Ð",
    priceUSD: 0.06,
    percentageChange: -0.9,
    image: "https://cryptologos.cc/logos/dogecoin-doge-logo.png",
  },
  {
    id: 7,
    code: "ADA",
    name: "Cardano",
    symbol: "₳",
    priceUSD: 0.26,
    percentageChange: 1.2,
    image: "https://cryptologos.cc/logos/cardano-ada-logo.png",
  },
  {
    id: 8,
    code: "DOT",
    name: "Polkadot",
    symbol: "DOT",
    priceUSD: 4.0,
    percentageChange: -2.1,
    image: "https://cryptologos.cc/logos/polkadot-new-dot-logo.png",
  },
  {
    id: 9,
    code: "MATIC",
    name: "Polygon",
    symbol: "MATIC",
    priceUSD: 0.8,
    percentageChange: 2.0,
    image: "https://cryptologos.cc/logos/polygon-matic-logo.png",
  },
  {
    id: 10,
    code: "LTC",
    name: "Litecoin",
    symbol: "Ł",
    priceUSD: 70,
    percentageChange: 0.5,
    image: "https://cryptologos.cc/logos/litecoin-ltc-logo.png",
  },
  {
    id: 11,
    code: "SHIB",
    name: "Shiba Inu",
    symbol: "SHIB",
    priceUSD: 0.000007,
    percentageChange: -0.8,
    image: "https://cryptologos.cc/logos/shiba-inu-shib-logo.png",
  },
  {
    id: 12,
    code: "AVAX",
    name: "Avalanche",
    symbol: "AVAX",
    priceUSD: 10,
    percentageChange: 1.7,
    image: "https://cryptologos.cc/logos/avalanche-avax-logo.png",
  },
  {
    id: 13,
    code: "TRX",
    name: "TRON",
    symbol: "TRX",
    priceUSD: 0.09,
    percentageChange: 2.9,
    image: "https://cryptologos.cc/logos/tron-trx-logo.png",
  },
  {
    id: 14,
    code: "UNI",
    name: "Uniswap",
    symbol: "UNI",
    priceUSD: 4.5,
    percentageChange: -1.5,
    image: "https://cryptologos.cc/logos/uniswap-uni-logo.png",
  },
  {
    id: 15,
    code: "XLM",
    name: "Stellar",
    symbol: "XLM",
    priceUSD: 0.1,
    percentageChange: 0.4,
    image: "https://cryptologos.cc/logos/stellar-xlm-logo.png",
  },
];
